localidades_argentina = {
    "Buenos Aires": ["La Plata", "Mar del Plata", "Bahía Blanca", "Tandil", "Olavarría"],
    "Catamarca": ["San Fernando del Valle de Catamarca", "Tinogasta", "Santa María", "Fiambalá", "Recreo"],
    "Chaco": ["Resistencia", "Presidencia Roque Sáenz Peña", "Villa Ángela", "Charata", "Castelli"],
    "Chubut": ["Rawson", "Comodoro Rivadavia", "Puerto Madryn", "Trelew", "Esquel"],
    "Córdoba": ["Córdoba", "Villa Carlos Paz", "Río Cuarto", "Villa María", "Alta Gracia"],
    "Corrientes": ["Corrientes", "Goya", "Mercedes", "Curuzú Cuatiá", "Paso de los Libres"],
    "Entre Ríos": ["Paraná", "Concordia", "Gualeguaychú", "Concepción del Uruguay", "Victoria"],
    "Formosa": ["Formosa", "Clorinda", "Pirané", "El Colorado", "Laguna Blanca"],
    "Jujuy": ["San Salvador de Jujuy", "Palpalá", "San Pedro", "Libertador General San Martín", "El Carmen"],
    "La Pampa": ["Santa Rosa", "General Pico", "Victorica", "General Acha", "Toay"],
    "La Rioja": ["La Rioja", "Chilecito", "Aimogasta", "Famatina", "Chamical"],
    "Mendoza": ["Mendoza", "San Rafael", "Godoy Cruz", "Luján de Cuyo", "Maipú"],
    "Misiones": ["Posadas", "Eldorado", "Oberá", "Iguazú", "Leandro N. Alem"],
    "Neuquén": ["Neuquén", "San Martín de los Andes", "Zapala", "Villa La Angostura", "Cutral Có"],
    "Río Negro": ["Viedma", "Bariloche", "General Roca", "Cipolletti", "San Antonio Oeste"],
    "Salta": ["Salta", "San Ramón de la Nueva Orán", "Tartagal", "Rosario de la Frontera", "Güemes"],
    "San Juan": ["San Juan", "Rawson", "Chimbas", "Pocito", "Caucete"],
    "San Luis": ["San Luis", "Villa Mercedes", "Merlo", "La Punta", "Juana Koslay"],
    "Santa Cruz": ["Río Gallegos", "Caleta Olivia", "El Calafate", "Pico Truncado", "Puerto Santa Cruz"],
    "Santa Fe": ["Santa Fe", "Rosario", "Rafaela", "Venado Tuerto", "Reconquista"],
    "Santiago del Estero": ["Santiago del Estero", "La Banda", "Fernández", "Frías", "Loreto"],
    "Tierra del Fuego": ["Ushuaia", "Río Grande", "Tolhuin", "Porvenir", "Puerto Williams"],
    "Tucumán": ["San Miguel de Tucumán", "Tafí Viejo", "Yerba Buena", "Concepción", "Monteros"]
}


provincias_en_db = {
    "1" :	"Buenos Aires",
    "2" :	"Córdoba",
    "3" :	"Santa Fe",
    "4" :	"Mendoza",
    "5" :	"Tucumán",
    "6" :	"Entre Ríos",
    "7" :	"Salta",
    "8" :	"Chaco",
    "9" :	"Corrientes",
    "10" :	"Misiones",
    "11" :	"San Juan",
    "12" :	"Jujuy",
    "13" :	"Río Negro",
    "14" :	"Neuquén",
    "15" :	"Formosa",
    "16" :	"San Luis",
    "17" :	"Catamarca",
    "18" :	"La Rioja",
    "19" :	"Chubut",
    "20" :	"La Pampa",
    "21" :	"Santa Cruz",
    "22" :	"Tierra del Fuego",
    "23" :	"Santiago del Estero"
}